name: Test backend

on:
    push:
    workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache-dependency-path: ./backend/go.sum

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Test with Go
        working-directory: ./backend
        run: go test -v ./...
