name: Test backend

on:
    push:
    workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Load Secret.json
        working-directory: ./backend
        run: |
          ./load-secret.sh "${{ secrets.SECRET }}"

      - name: Test with Go
        working-directory: ./backend
        run: go test -v ./...
