name: Test backend

on:
    push:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        working-directory: ./backend
        run: go get .

      - name: Test with Go
        working-directory: ./backend
        run: go test -v ./...
